version: '3.8'

services:
  mysql:
      image: mysql:latest
      container_name: mysql
      restart: unless-stopped
      env_file: ./.env
      environment:
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      volumes:
        - ./db_data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql      
      networks:
      - app-network  
  app:
    depends_on:
      - mysql
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - app-network
  
    
volumes:
  db_data:
networks:
  app-network:
